baseURL: "https://pandirabhishek.github.io/"
languageCode: en-us
title: Abhishek Pandir
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Abhishek Pandir"
    subtitle: I am an experienced ML engineer with experience in building complete end-to-end ML solutions from the research phase to final delivery. I have also worked on building websites and mobile apps.
    imageUrl: "home/casual.jpeg"
    imageWidth: 200
    imageHeight: 220
    buttons:
      - name: Resume
        url: ""
      - name: Blog
        url: /blog

  # List View
  hideDescriptionInList: false

  social:
    - name: "email"
      url: "mailto:pandirabhishek2001@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abdurrahmankalim"
    - name: "github"
      url: "https://github.com/arkalim"
    - name: "youtube"
      url: "https://www.youtube.com/c/AbdurRahmanKalim"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - JSON


# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
